const userslist = [
  {
    id: '1',
    firstName: 'Roman',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Admin',
    phone: '+380934400536',
  },
  {
    id: '2',
    firstName: 'Andriy',
    lastName: 'Romanyuk',
    email: 'natanbfhr@gmail.com',
    role: 'Manager',
    phone: '+380934400536',
  },
  {
    id: '3',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '4',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '5',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '6',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '7',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '8',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '9',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '10',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '11',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '12',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '13',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '14',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '15',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
  {
    id: '16',
    firstName: 'Taras',
    lastName: 'Romanyuk',
    email: 'nataniel.rr@gmail.com',
    role: 'Employee',
    phone: '+380934400536',
  },
];
export default userslist;
